### ISSUE TITLE
React hook for fetching metrics from prometheus

### ISSUE THREAD

**Issue by alexrefshauge** [P3-Hype/SRAMS-frontend#3]

**Comment by alexrefshauge** [comment]
@LeUnioo Støtte på denne pakke, måske den kan bruges?
https://www.npmjs.com/package/prometheus-query

**Comment by LeUnioo** [comment]
Jeg har fundet følgende hjemmesider måske kan bruge:
https://www.asserts.ai/blog/react-and-prometheus/ 


Derudover har jeg også spurgt min lille ven (ChatGBT), som er kommet med følgende svar

--------- ChatGBT-----------
To fetch metrics from Prometheus in a React application, you can create a custom React hook that uses the `fetch` API or a library like Axios to make HTTP requests to the Prometheus server's API. Here's an example of a custom React hook that fetches metrics from Prometheus:

***********javascript***********

import { useState, useEffect } from 'react';

function usePrometheusMetrics(query) {
  const [metrics, setMetrics] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function fetchMetrics() {
      try {
        // Replace 'prometheus-url' with the actual URL of your Prometheus server and 'query' with your Prometheus query.
        const response = await fetch(`http://prometheus-url/api/v1/query?query=${query}`);
        if (!response.ok) {
          throw new Error(`Failed to fetch metrics: ${response.statusText}`);
        }
        const data = await response.json();
        setMetrics(data.data.result);
        setLoading(false);
        setError(null);
      } catch (err) {
        setError(err);
        setLoading(false);
      }
    }

    fetchMetrics();
  }, [query]);

  return { metrics, loading, error };
}

export default usePrometheusMetrics;
```

Here's how you can use this hook in your React component:
***********javascript***********

import React, { useEffect } from 'react';
import usePrometheusMetrics from './usePrometheusMetrics';

function MetricsComponent() {
  const { metrics, loading, error } = usePrometheusMetrics('your-prometheus-query');

  useEffect(() => {
    if (loading) {
      // Handle loading state
    } else if (error) {
      // Handle error state
    } else {
      // Render metrics data
      console.log(metrics);
    }
  }, [metrics, loading, error]);

  return (
    <div>
      {loading && <p>Loading...</p>}
      {error && <p>Error: {error.message}</p>}
      {/* Render your metrics data here */}
    </div>
  );
}

export default MetricsComponent;
```

Make sure to replace `'prometheus-url'` with the actual URL of your Prometheus server and `'your-prometheus-query'` with the Prometheus query you want to fetch. This hook will handle the loading and error states and provide you with the metrics data once it's fetched.

**Comment by alexrefshauge** [comment]
Skide godt, jeg tænker at det giver god mening at skrive en hook som GPT foreslår der
