### ISSUE TITLE
header

### ISSUE THREAD

**Issue by TobiasABay** [P3-Hype/SRAMS-frontend#8]
![Image](https://github.com/P3-Hype/SRAMS-frontend/assets/45756799/739f920c-5172-4480-8c5d-ec7c33c0a5f1)

Header with SRAMS logo and info link

**Comment by M4N0H4R** [comment]
Hi there!

I came across this issue and would like to work on it. Before I dive in, I wanted to confirm a few things and seek some guidance:

1. Is this issue still open and available for contributions?
2. Can someone provide me with more details or context about the issue?
3. Is there any specific approach or solution in mind for addressing this issue?
4. Are there any coding standards or guidelines I should be aware of for this project?

I'm really excited about getting involved in this project, and any help or direction you can provide would be greatly appreciated. I'm open to feedback and learning along the way, so please feel free to share any advice or recommendations.

Looking forward to your response!

Best regards,
MANU

**Comment by TobiasABay** [comment]
You cant join dude, it is a school project - Make your own cool srams project
